# Generated by Django 3.0.5 on 2020-04-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome_exibir',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
