# Generated by Django 3.0.5 on 2020-05-15 15:35

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem_home',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem na Home Page'),
        ),
        migrations.CreateModel(
            name='ArtigoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Publicação')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Artigo')),
            ],
            options={
                'verbose_name': 'Imagem Artigo',
                'verbose_name_plural': 'Imagens do Artigo',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
