# Generated by Django 3.0.5 on 2020-04-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome_exibir'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
